import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = resolve(root, 'src', 'generated');
const outFile = resolve(outDir, 'build-info.mjs');

let commit = '';
let commitFull = '';
try {
  commitFull = execSync('git rev-parse HEAD', { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] })
    .toString()
    .trim();
  commit = execSync('git rev-parse --short=8 HEAD', { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] })
    .toString()
    .trim();
} catch {
  commit = 'development';
}

let packageVersion = 'unknown';
try {
  const pkg = JSON.parse(
    await import('node:fs').then(({ readFileSync }) =>
      readFileSync(resolve(root, 'package.json'), 'utf8'),
    ),
  );
  packageVersion = pkg.version ?? 'unknown';
} catch {
  /* ignore */
}

let astroVersion = 'unknown';
try {
  const pkg = JSON.parse(
    await import('node:fs').then(({ readFileSync }) =>
      readFileSync(resolve(root, 'node_modules', 'astro', 'package.json'), 'utf8'),
    ),
  );
  astroVersion = pkg.version ?? 'unknown';
} catch {
  /* ignore */
}

const buildInfo = {
  packageVersion,
  astroVersion,
  commit,
  commitFull,
  builtAt: new Date().toISOString(),
  mode: 'static',
};

mkdirSync(outDir, { recursive: true });
writeFileSync(
  outFile,
  `// Generated by scripts/build-info.mjs — do not edit.\nexport const buildInfo = ${JSON.stringify(buildInfo, null, 2)};\n`,
);
console.log(`build-info: commit=${commit} astro=${astroVersion} pkg=${packageVersion}`);